# Generated by Django 6.0.2 on 2026-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_faculty_alter_lecturer_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
