# Generated by Django 6.0.2 on 2026-03-02 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_faculty_name_alter_lecturer_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
