# Generated by Django 6.0.2 on 2026-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_review_downvotes_review_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subject',
            field=models.CharField(default='', help_text='e.g., Data Structures, Operating Systems', max_length=100),
            preserve_default=False,
        ),
    ]
