# Generated by Django 6.0.2 on 2026-03-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
